### PR TITLE
Added profileUrl as a configurable url; allow to pass an object to signup endpoint

### PR DESCRIPTION
**Pull request by vcardins**

### CODE REVIEW

**Comment by paulvanbladel** [comment]
Ok, I see now, it's a file related to visual studio code.
No worries, we can leave that file.

**Comment by paulvanbladel** [comment]
Victor,
Pull request merged.
Thanks a lot.

**Comment by vcardins** [comment]
Excellent, Paul ! I'm glad I could help. Sorry about not mentioning the jsconfig.json file. I'll be playing with it now on and will help once I get new ideas.
Thank you for this great bit !!

**Comment by paulvanbladel** [comment]
jsconfig is fine. Code is a promising editor !
Maybe something we could look into:

I'm wondering if we can  get rid of something in app.js in the sample app.
In app.js there is the activate method containing:
```
activate(){
    this.httpClientConfig.configure();
    this.appRouterConfig.configure();
  }
```
The second line is ok, and it part of the app rather than related to the aureliauth plugin.
The first line configures the httpClient and assures the token is added automatically when the client is authenticated.
I tried to find a way to do this inside the plugin rather than triggering it from the app.
Any idea?

**Comment by vcardins** [comment]
I'll dig more into the codebase now on and see what I can come up with. I've implemented a httpClient wrapper for Angular2, maybe I can borrow something from.

**Comment by vcardins** [comment]
Hi Paul, I'm rewriting the plugin in TypeScript and also I'll try to improve what I can. If you have other suggestions I can also help on.

**Comment by paulvanbladel** [comment]
Cool.

Functionality to ad hoc disable the inclusion of the token would be nice.

I will think about other stuff, but currently on holiday:)
Op 13-jul.-2015 12:26 schreef "Victor Cardins" <notifications@github.com>:

**Pull request merged**
